name = "cloud-database1"
main = "worker.js"
compatibility_date = "2025-01-01"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "MY_DATABASE"
class_name = "MyDatabase"

# Correct syntax for free plan
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyDatabase"]
