name = "cloudflaredb-pages"
main = "worker.js"
compatibility_date = "2025-01-01"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "MY_DATABASE"
class_name = "MyDatabase"

# Database migrations
[[migrations]]
tag = "v1"
new_classes = ["MyDatabase"]
